### ISSUE TITLE
Feel like supporting LostKng.bf ?

### ISSUE THREAD

**Issue by rdebath** [none-None1/Interpret-Esolangs-Online#1]
This BF code: https://raw.githubusercontent.com/rdebath/LostKingdom/gh-pages/LostKng.b

Needs to run like this: http://rdebath.github.io/LostKingdom/

**Comment by none-None1** [comment]
This interpreter is non-interactive. If I have time I will make an interactive BF interpreter.

**Comment by none-None1** [comment]
And I made this [interactive BF interpreter](https://none1.pyscriptapps.com/brainf/latest/) seconds ago, just copy the source code of the bf program and run!

**Comment by rdebath** [comment]
Seems that it reprints the prompt for every character input rather than just at the start of a new line.
Also the `\n` character looks double spaced on output.

<s>It doesn't work for LostKng yet, (too big probably) but</s> it does work for this ...
[Prime2-multi.txt](https://github.com/none-None1/Interpret-Esolangs-Online/files/15137969/Prime2-multi.txt)

Nevermind, LostKng seems ok eventually; I guess I have a slow machine.
It is double spaced too though.

**Comment by none-None1** [comment]
LostKng works smoothly on my machine，but I'm not sure about the double spaced problem. You can see the source (in Python) by clicking the view source button at the bottom right corner. And if you can fix that, tell me how.
